### ISSUE TITLE
Have minikubeDockerBuild be more helpful by providing default parameters.

### ISSUE THREAD

**Issue by coollog** [GoogleCloudPlatform/minikube-build-tools-for-java#14]
Currently, `minikubeDockerBuild` (#7) takes a [`context` and `flags`](https://docs.docker.com/engine/reference/commandline/build/).

We want it to be more helpful by providing some default `docker build` parameters as part of the task configuration:
 
~~1. `dockerfile`- configures the task with `-f <value>`
    - Default: `src/main/docker/Dockerfile`
    - Reason: since we don't really expect to find Dockerfile in the root of a Gradle project.~~
1. Reason: save the user the hassle of having to define build context/Dockerfile location themselves.
    1. **IN PROGRESS (#16)** A separate task `prepareMinikubeDockerBuild` that prepares the context to use for `minikubeDockerBuild`. Takes parameters:
        - `context`: the task syncs this to `build/docker`
            - Default: `build/libs`
        - `dockerfile`: the task syncs this to `build/docker/Dockerfile`
            - Default: `src/main/docker/Dockerfile`
    1. **IN PROGRESS (#17) ** Have `minikubeDockerBuild` use `build/docker` for its context and depends on the successful execution of the `prepareMinikubeDockerBuild` task.
2. **IN PROGRESS (#15)** `tag` - configures the task with `-t <value>`
    - Default: `${project.group}/${project.name}:${project.version}`
    - Reason: provides the user with a convenient tag to refer to the image with

Please comment with more ideas about what configuration to provide. The above list will be updated with more ideas.

**Comment by r2d4** [comment]
It might be useful to auto-populate the "tag" parameter with something like "$ORGANIZATION/$PROJECT_NAME:$VERISON"

**Comment by coollog** [comment]
Okay, how about having a field like:

`imageTagConfig` - nested with properties: `organization`, `projectName`, `version`
    (Configures the task with `-t <organization>/<projectName>:<version>`)

@loosebazooka

**Comment by coollog** [comment]
Also, @loosebazooka , it seems that the Dockerfile must be in the build context, so a default context of `build/libs` with a default Dockerfile of `src/main/docker/Dockerfile` would not work.

**Comment by loosebazooka** [comment]
I think you can just have those be base properties on the task.

**Comment by coollog** [comment]
What if the user wanted to not use the auto-populated task? Should we include another property called `useAutoGeneratedTag` that defaults to true?

**Comment by loosebazooka** [comment]
I'm not sure what the override order is, but if the user uses -t in "flags", that should override whatever we've configured from `imageTagConfig` (or whatever that config ends up being)

**Comment by coollog** [comment]
The user can actually specify multiple -t tags, and it will tag the same image with each tag that is provided, so there is no override.

**Comment by coollog** [comment]
Closed pending design for new way of building with the Minikube Docker environment.
