### ISSUE TITLE
Invert dependency between AbstractHashingBlob and its subclasses.

### ISSUE THREAD

**Issue by coollog** [GoogleCloudPlatform/minikube-build-tools-for-java#64]
`AbstractHashingBlob.java`
"In general, I would like to lean towards the composition model for code sharing. Perhaps HashingStringBlob and HashWriterBlob could share this code through a third object that is passed to them?" - @loosebazooka

**Comment by loosebazooka** [comment]
I ran into this too with InputStreamBlob and FileStreamBlob, you can compose with templates if you chose to do so.
