### ISSUE TITLE
minikubeDockerBuild

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/minikube-build-tools-for-java#7]
run a docker build into the minikube env.

command line equivalent 
```
> eval $(minikube docker-env)
> docker build ....
```

Probably exposed to the user as `minikubeDockerBuild`, unfortunately there's no official docker plugin to link to, so we might have to use the docker java api directly to initiate a build.

**Comment by loosebazooka** [comment]
you can use https://github.com/kubernetes/minikube/pull/1792 to obtain the docker config for minikube

**Comment by coollog** [comment]
Starting with getting the minikube docker env vars, will take these steps:

1) Create a shared utility class called CommandExecutor that can run a shell command and get the output.
2) Use this CommandExecutor in a new DockerBuildTask to retrieve the minikube docker env vars.

**Comment by coollog** [comment]
Then will take these steps:
